apiVersion: cloud.redhat.com/v1alpha1
kind: FrontendEnvironment
metadata:
  name: env-boot
spec: 
# Use hack/update-sso.sh to compute this for dev-sso auth domain 
  sso: "https://keycloak-dev-sso.apps.9de5860cb7ec91775ccf.hypershift.aws-2.ci.openshift.org/auth/" 
  ingressClass: openshift-default
  hostname: https://a333d6e9d86204574863d88983f71f07-1d4d257a8e755b52.elb.us-east-1.amazonaws.com:6443
